import { Document, Packer, Paragraph, HeadingLevel, TextRun, AlignmentType, BorderStyle } from "docx";
import { saveAs } from "file-saver";
import { ReportData } from "../../../report/page";

function contentParagraphs(text: string): Paragraph[] {
  return text
    .split("\n")
    .map(
      (line) =>
        new Paragraph({
          children: [new TextRun({ text: line })],
        })
    );
}

function sectionHeading(title: string): Paragraph {
  return new Paragraph({
    text: title,
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 400, after: 200 },
    border: {
      bottom: {
        color: "AAAAAA",
        space: 1,
        style: BorderStyle.SINGLE,
        size: 6,
      },
    },
  });
}

export async function exportDocx(data: ReportData) {
  const doc = new Document({
    sections: [
      {
        children: [
          // Title
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
            children: [
              new TextRun({
                text: "AI Planning Report",
                bold: true,
              }),
            ],
          }),

          // Subtitle
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
            children: [
              new TextRun({
                text: "Generated by AI Planning Agent",
                size: 22,
                color: "888888",
                italics: true,
              }),
            ],
          }),

          sectionHeading("Problem Breakdown"),
          ...contentParagraphs(data.problemBreakdown),

          sectionHeading("Stakeholders"),
          ...contentParagraphs(data.stakeholders),

          sectionHeading("Solution Approach"),
          ...contentParagraphs(data.solutionApproach),

          sectionHeading("Action Plan"),
          ...contentParagraphs(data.actionPlan),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, "report.docx");
}