import { ReportData } from "../../../report/page";
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
import { TDocumentDefinitions, ContentStack, ContentText } from "pdfmake/interfaces";

(pdfMake as any).vfs = (pdfFonts as any).vfs;

const COLORS = {
  primary:   "#0f172a", // slate-950
  heading:   "#1e293b", // slate-800
  accent:    "#f59e0b", // amber-400
  muted:     "#64748b", // slate-500
  border:    "#e2e8f0", // slate-200
  white:     "#ffffff",
};

const SECTION_META: { key: keyof ReportData; title: string; accentColor: string }[] = [
  { key: "problemBreakdown", title: "Problem Breakdown", accentColor: "#f43f5e" },
  { key: "stakeholders",     title: "Stakeholders",      accentColor: "#0ea5e9" },
  { key: "solutionApproach", title: "Solution Approach", accentColor: "#8b5cf6" },
  { key: "actionPlan",       title: "Action Plan",       accentColor: "#f59e0b" },
];

function buildSection(title: string, content: string, accentColor: string): ContentStack {
  const lines = content.split("\n").filter(Boolean);

  return {
    stack: [
      // Accent bar via a filled rectangle canvas
      {
        canvas: [
          {
            type: "rect",
            x: 0, y: 0,
            w: 515, h: 3,
            r: 2,
            color: accentColor,
          },
        ],
        margin: [0, 0, 0, 8],
      },
      // Section heading
      {
        text: title,
        fontSize: 13,
        bold: true,
        color: COLORS.heading,
        margin: [0, 0, 0, 6],
      } as ContentText,
      // Content lines
      ...lines.map((line) => ({
        text: line,
        fontSize: 10,
        color: COLORS.primary,
        lineHeight: 1.6,
        margin: [0, 0, 0, 3],
      } as ContentText)),
    ],
    margin: [0, 0, 0, 24],
  };
}

export function exportPDF(data: ReportData): void {
  const docDefinition: TDocumentDefinitions = {
    pageSize: "A4",
    pageMargins: [40, 56, 40, 56],
    defaultStyle: {
      font: "Roboto",
      fontSize: 10,
      color: COLORS.primary,
    },
    content: [
      // Title
      {
        text: "AI Planning Report",
        fontSize: 22,
        bold: true,
        color: COLORS.heading,
        alignment: "center",
        margin: [0, 0, 0, 6],
      } as ContentText,
      // Subtitle
      {
        text: "Generated by AI Planning Agent",
        fontSize: 10,
        color: COLORS.muted,
        alignment: "center",
        italics: true,
        margin: [0, 0, 0, 32],
      } as ContentText,
      // Divider
      {
        canvas: [
          {
            type: "line",
            x1: 0, y1: 0,
            x2: 515, y2: 0,
            lineWidth: 1,
            lineColor: COLORS.border,
          },
        ],
        margin: [0, 0, 0, 28],
      },
      // Sections
      ...SECTION_META.map(({ key, title, accentColor }) =>
        buildSection(title, data[key], accentColor)
      ),
    ],
    footer: (currentPage: number, pageCount: number) => ({
      text: `${currentPage} / ${pageCount}`,
      alignment: "center",
      fontSize: 8,
      color: COLORS.muted,
      margin: [0, 8, 0, 0],
    }),
  };

  pdfMake.createPdf(docDefinition).download("ai-report.pdf");
}